pub struct CompDef {
    pub name: &'static str,
    pub nation: Option<&'static str>,
    pub tier: Option<i64>,
    pub teams: i64,
}

pub const ALL_COMPS: &[CompDef] = &[
    CompDef { name: "Primera División de Fútbol Sala", nation: Some("España"), tier: Some(1), teams: 16 },
    CompDef { name: "Segunda División B - Grupo 1", nation: Some("España"), tier: Some(3), teams: 10 },
    CompDef { name: "Segunda División B - Grupo 2", nation: Some("España"), tier: Some(3), teams: 10 },
    CompDef { name: "Segunda División B - Grupo 3", nation: Some("España"), tier: Some(3), teams: 10 },
    CompDef { name: "Segunda División B - Grupo 4", nation: Some("España"), tier: Some(3), teams: 10 },
    CompDef { name: "Segunda División B - Grupo 5", nation: Some("España"), tier: Some(3), teams: 10 },
    CompDef { name: "Segunda División B - Grupo 6", nation: Some("España"), tier: Some(3), teams: 10 },
    CompDef { name: "Copa de España de Fútbol Sala", nation: Some("España"), tier: None, teams: 32 },
    CompDef { name: "Supercopa de España", nation: Some("España"), tier: None, teams: 4 },
    CompDef { name: "Liga Nacional de Futsal (LNF)", nation: Some("Brasil"), tier: Some(1), teams: 16 },
    CompDef { name: "Taça Brasil de Futsal", nation: Some("Brasil"), tier: None, teams: 32 },
    CompDef { name: "Liga Placard", nation: Some("Portugal"), tier: Some(1), teams: 14 },
    CompDef { name: "Taça de Portugal de Futsal", nation: Some("Portugal"), tier: None, teams: 24 },
    CompDef { name: "Superliga Rusa de Fútbol Sala", nation: Some("Rusia"), tier: Some(1), teams: 14 },
    CompDef { name: "Serie A Futsal", nation: Some("Italia"), tier: Some(1), teams: 14 },
    CompDef { name: "Serie A2 Futsal", nation: Some("Italia"), tier: Some(2), teams: 14 },
    CompDef { name: "Kazakhstani Futsal Championship", nation: Some("Kazajistán"), tier: Some(1), teams: 10 },
    CompDef { name: "Iranian Futsal Super League", nation: Some("Irán"), tier: Some(1), teams: 12 },
    CompDef { name: "Argentine Futsal Primera División", nation: Some("Argentina"), tier: Some(1), teams: 12 },
    CompDef { name: "Ukrainian Futsal Extraliga", nation: Some("Ucrania"), tier: Some(1), teams: 10 },
    CompDef { name: "French Futsal D1", nation: Some("Francia"), tier: Some(1), teams: 12 },
    CompDef { name: "Japan Futsal League (F.League)", nation: Some("Japón"), tier: Some(1), teams: 10 },
    CompDef { name: "Croatian First Futsal League", nation: Some("Croacia"), tier: Some(1), teams: 10 },
    CompDef { name: "Czech Futsal First League", nation: Some("Rep. Checa"), tier: Some(1), teams: 10 },
    CompDef { name: "Serbian Futsal League", nation: Some("Serbia"), tier: Some(1), teams: 10 },
    CompDef { name: "Polish Futsal Ekstraklasa", nation: Some("Polonia"), tier: Some(1), teams: 12 },
    CompDef { name: "Azerbaijani Futsal Higher League", nation: Some("Azerbaiyán"), tier: Some(1), teams: 8 },
    CompDef { name: "Colombian Futsal League", nation: Some("Colombia"), tier: Some(1), teams: 10 },
    CompDef { name: "Thai Futsal League", nation: Some("Tailandia"), tier: Some(1), teams: 12 },
    CompDef { name: "Liga de Futsal de Uruguay", nation: Some("Uruguay"), tier: Some(1), teams: 10 },
    CompDef { name: "Mundial de Fútbol Sala", nation: None, tier: None, teams: 24 },
    CompDef { name: "Copa América de Fútbol Sala", nation: None, tier: None, teams: 10 },
    CompDef { name: "Eurocopa de Fútbol Sala", nation: None, tier: None, teams: 16 },
    CompDef { name: "AFC Futsal Asian Cup", nation: None, tier: None, teams: 16 },
    CompDef { name: "CAF Futsal Africa Cup of Nations", nation: None, tier: None, teams: 12 },
    CompDef { name: "CONMEBOL Futsal Championship", nation: None, tier: None, teams: 10 },
    CompDef { name: "OFC Futsal Men Cup", nation: None, tier: None, teams: 8 },
];

pub const ALL_NATIONS: &[(&str, &str, i64, i64)] = &[
    ("España", "UEFA", 920, 92),
    ("Brasil", "CONMEBOL", 950, 95),
    ("Portugal", "UEFA", 900, 88),
    ("Rusia", "UEFA", 820, 82),
    ("Italia", "UEFA", 850, 86),
    ("Kazajistán", "UEFA", 720, 68),
    ("Irán", "AFC", 800, 80),
    ("Argentina", "CONMEBOL", 830, 84),
    ("Ucrania", "UEFA", 740, 72),
    ("Francia", "UEFA", 760, 74),
    ("Japón", "AFC", 730, 71),
    ("Croacia", "UEFA", 750, 73),
    ("Rep. Checa", "UEFA", 730, 71),
    ("Serbia", "UEFA", 710, 69),
    ("Polonia", "UEFA", 700, 68),
    ("Azerbaiyán", "UEFA", 680, 65),
    ("Colombia", "CONMEBOL", 720, 70),
    ("Tailandia", "AFC", 690, 67),
    ("Uruguay", "CONMEBOL", 700, 68),
    ("Alemania", "UEFA", 600, 60),
    ("Inglaterra", "UEFA", 580, 58),
    ("Estados Unidos", "CONCACAF", 550, 55),
    ("Marruecos", "CAF", 620, 62),
    ("Egipto", "CAF", 610, 61),
    ("Australia", "AFC", 600, 60),
    ("Paraguay", "CONMEBOL", 680, 66),
];

